// Popular cities shown initially (choice overload fix)
export const POPULAR_CITIES = [
	"London",
	"Berlin",
	"Amsterdam",
	"Paris",
	"Dublin",
	"Barcelona",
	"Madrid",
];

// All available cities (shown when user clicks "Show more")
export const ALL_CITIES = [
	"Dublin",
	"London",
	"Paris",
	"Amsterdam",
	"Manchester",
	"Birmingham",
	"Belfast",
	"Madrid",
	"Barcelona",
	"Berlin",
	"Hamburg",
	"Munich",
	"Zurich",
	"Milan",
	"Rome",
	"Brussels",
	"Stockholm",
	"Copenhagen",
	"Vienna",
	"Prague",
	"Warsaw",
];

// Backwards compatibility - default to popular cities
export const CITIES = POPULAR_CITIES;

export const LANGUAGES = [
	// Most common EU languages
	"English",
	"French",
	"German",
	"Spanish",
	"Italian",
	"Dutch",
	"Portuguese",
	// Additional EU languages
	"Polish",
	"Swedish",
	"Danish",
	"Finnish",
	"Czech",
	"Romanian",
	"Hungarian",
	"Greek",
	"Bulgarian",
	"Croatian",
	"Serbian",
	"Slovak",
	"Slovenian",
	"Estonian",
	"Latvian",
	"Lithuanian",
	"Ukrainian",
	// Middle Eastern & Central Asian (common visa seekers)
	"Arabic",
	"Turkish",
	"Hebrew",
	"Persian",
	"Farsi",
	"Urdu",
	// Asian languages (common visa seekers)
	"Japanese",
	"Chinese",
	"Mandarin",
	"Cantonese",
	"Korean",
	"Hindi",
	"Thai",
	"Vietnamese",
	"Indonesian",
	"Tagalog",
	"Malay",
	"Bengali",
	"Tamil",
	"Telugu",
	// Other common languages
	"Russian",
];

export const INDUSTRIES = [
	"Technology",
	"Finance",
	"Consulting",
	"Healthcare",
	"Retail",
	"Manufacturing",
	"Energy",
	"Media",
	"Education",
	"Government",
	"Non-profit",
	"Real Estate",
	"Transportation",
	"Automotive",
	"Fashion",
	"Food & Beverage",
	"Travel",
	"Other",
];

export const COMPANY_SIZES = [
	{ value: "startup", label: "Startup (1-50)", emoji: "" },
	{ value: "scaleup", label: "Scale-up (50-500)", emoji: "" },
	{ value: "enterprise", label: "Enterprise (500+)", emoji: "" },
	{ value: "any", label: "Any Size", emoji: "" },
];

export const COMMON_SKILLS = [
	"Excel",
	"PowerPoint",
	"Word",
	"Python",
	"R",
	"SQL",
	"PowerBI",
	"Tableau",
	"Google Analytics",
	"Salesforce",
	"HubSpot",
	"Jira",
	"Confluence",
	"Slack",
	"Microsoft Office",
	"Google Workspace",
	"Adobe Creative Suite",
	"Canva",
	"Data Analysis",
	"Project Management",
	"Digital Marketing",
	"Social Media",
	"Email Marketing",
	"Content Creation",
	"Research",
	"Presentation Skills",
	"Communication",
	"Leadership",
	"Problem Solving",
	"Analytical Thinking",
];

export const COMPANIES = [
	"Global Consulting Firms",
	"Startups / Scaleups",
	"Tech Giants",
	"Investment Firms / VCs",
	"Multinationals",
	"Public Sector / NGOs",
	"B2B SaaS",
	"Financial Services",
];

export const CAREER_PATHS = [
	{
		value: "strategy",
		label: "Strategy & Business Design",
		emoji: "",
		popularRoles: [
			"Business Analyst",
			"Associate Consultant",
			"Strategy Analyst",
			"Junior Consultant",
			"Consulting Intern"
		],
		roles: [
			"Business Analyst",
			"Associate Consultant",
			"Junior Consultant",
			"Strategy Analyst",
			"Consulting Intern",
			"Junior Business Analyst",
			"Transformation Analyst",
			"Management Consulting Intern",
			"Growth Consultant",
			"Business Analyst Trainee",
			"Junior Associate",
			"Strategy Consultant",
			"Digital Transformation Analyst",
			"Operations Excellence Consultant",
			"Business Strategy Intern",
		],
	},
	{
		value: "data",
		label: "Data & Analytics",
		emoji: "",
		popularRoles: [
			"Data Analyst",
			"Junior Data Analyst",
			"Analytics Intern",
			"Business Intelligence Intern",
			"Junior Data Scientist"
		],
		roles: [
			"Data Analyst",
			"Junior Data Analyst",
			"Analytics Intern",
			"Business Intelligence Intern",
			"Data Analyst Trainee",
			"Junior Data Scientist",
			"Data Science Trainee",
			"Junior Data Engineer",
			"BI Engineer Intern",
			"Analytics Associate",
			"Data Analytics Graduate",
			"Insights Analyst",
			"Junior BI Developer",
			"Data Assistant",
			"Research & Analytics Intern",
		],
	},
	{
		value: "sales",
		label: "Sales & Client Success",
		emoji: "",
		popularRoles: [
			"Sales Development Representative (SDR)",
			"Business Development Representative (BDR)",
			"Inside Sales Representative",
			"Account Executive",
			"Customer Success Associate"
		],
		roles: [
			"Sales Development Representative (SDR)",
			"Business Development Representative (BDR)",
			"Inside Sales Representative",
			"Account Executive",
			"Business Development Associate",
			"Sales Trainee",
			"Customer Success Associate",
			"Revenue Operations Analyst",
			"Sales Operations Analyst",
			"Graduate Sales Programme",
			"Business Development Intern",
			"Channel Sales Associate",
			"Account Development Representative",
			"Junior Sales Executive",
			"Client Success Manager",
		],
	},
	{
		value: "marketing",
		label: "Marketing & Growth",
		emoji: "",
		popularRoles: [
			"Marketing Intern",
			"Digital Marketing Assistant",
			"Marketing Coordinator",
			"Social Media Intern",
			"Growth Marketing Intern"
		],
		roles: [
			"Marketing Intern",
			"Social Media Intern",
			"Digital Marketing Assistant",
			"Marketing Coordinator",
			"Growth Marketing Intern",
			"Content Marketing Intern",
			"Brand Assistant",
			"Marketing Assistant",
			"Junior Marketing Associate",
			"Email Marketing Trainee",
			"SEO/SEM Intern",
			"Trade Marketing Intern",
			"Marketing Graduate Programme",
			"Junior B2B Marketing Coordinator",
			"Marketing Campaign Assistant",
		],
	},
	{
		value: "finance",
		label: "Finance & Investment",
		emoji: "",
		popularRoles: [
			"Financial Analyst",
			"Finance Intern",
			"Investment Banking Analyst",
			"Risk Analyst",
			"Audit Associate"
		],
		roles: [
			"Financial Analyst",
			"Finance Intern",
			"Investment Banking Analyst",
			"Risk Analyst",
			"Audit Associate",
			"Finance Trainee",
			"FP&A Analyst",
			"Credit Analyst",
			"Investment Analyst",
			"Junior Accountant",
			"Corporate Finance Analyst",
			"M&A Analyst",
			"Treasury Analyst",
			"Junior Tax Associate",
			"Finance Graduate",
		],
	},
	{
		value: "operations",
		label: "Operations & Supply Chain",
		emoji: "",
		popularRoles: [
			"Operations Analyst",
			"Supply Chain Analyst",
			"Logistics Analyst",
			"Procurement Analyst",
			"Operations Intern"
		],
		roles: [
			"Operations Analyst",
			"Supply Chain Analyst",
			"Logistics Analyst",
			"Procurement Analyst",
			"Operations Intern",
			"Inventory Planner",
			"Operations Coordinator",
			"Supply Chain Trainee",
			"Logistics Planning Graduate",
			"Demand Planning Intern",
			"Operations Management Trainee",
			"Fulfilment Specialist",
			"Sourcing Analyst",
			"Process Improvement Analyst",
			"Supply Chain Graduate",
		],
	},
	{
		value: "product",
		label: "Product & Innovation",
		emoji: "",
		popularRoles: [
			"Associate Product Manager (APM)",
			"Product Analyst",
			"Product Management Intern",
			"Junior Product Manager",
			"Product Designer"
		],
		roles: [
			"Associate Product Manager (APM)",
			"Product Analyst",
			"Product Management Intern",
			"Junior Product Manager",
			"Product Operations Associate",
			"Product Designer",
			"UX Intern",
			"Product Research Assistant",
			"Innovation Analyst",
			"Product Development Coordinator",
			"Product Marketing Assistant",
			"Product Owner Graduate",
			"Assistant Product Manager",
			"Product Strategy Intern",
			"Technical Product Specialist",
		],
	},
	{
		value: "tech",
		label: "Tech & Transformation",
		emoji: "",
		popularRoles: [
			"Software Engineer Intern",
			"Cloud Engineer Intern",
			"DevOps Engineer Intern",
			"Data Engineer Intern",
			"Systems Analyst"
		],
		roles: [
			"Software Engineer Intern",
			"Cloud Engineer Intern",
			"DevOps Engineer Intern",
			"Data Engineer Intern",
			"Systems Analyst",
			"IT Support Analyst",
			"Application Support Analyst",
			"Technology Analyst",
			"QA/Test Analyst",
			"Platform Engineer Intern",
			"Cybersecurity Analyst",
			"IT Operations Trainee",
			"Technical Consultant",
			"Solutions Engineer Graduate",
			"IT Business Analyst",
		],
	},
	{
		value: "sustainability",
		label: "Sustainability & ESG",
		emoji: "",
		popularRoles: [
			"ESG Intern",
			"Sustainability Strategy Intern",
			"Junior ESG Analyst",
			"Sustainability Graduate Programme",
			"ESG Data Analyst Intern"
		],
		roles: [
			"ESG Intern",
			"Sustainability Strategy Intern",
			"Junior ESG Analyst",
			"Sustainability Graduate Programme",
			"ESG Data Analyst Intern",
			"Corporate Responsibility Intern",
			"Environmental Analyst",
			"Sustainability Reporting Trainee",
			"Climate Analyst",
			"Sustainable Finance Analyst",
			"ESG Assurance Intern",
			"Sustainability Communications Intern",
			"Junior Impact Analyst",
			"Sustainability Operations Assistant",
			"Green Finance Analyst",
		],
	},
	{
		value: "unsure",
		label: "Not Sure Yet / General",
		emoji: "",
		popularRoles: [
			"Graduate Trainee",
			"Rotational Graduate Program",
			"Management Trainee",
			"Business Graduate Analyst",
			"Entry Level Program Associate"
		],
		roles: [
			"Graduate Trainee",
			"Rotational Graduate Program",
			"Management Trainee",
			"Business Graduate Analyst",
			"Entry Level Program Associate",
			"Future Leaders Programme",
			"General Analyst",
			"Operations Graduate",
			"Commercial Graduate",
			"Early Careers Program",
			"Project Coordinator",
			"Business Operations Analyst",
			"Emerging Leaders Associate",
			"Corporate Graduate Programme",
			"Generalist Trainee",
		],
	},
];
